name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: af-south-1
  TF_WORKING_DIR: infra/environments/dev
  AWS_ROLE_ARN: arn:aws:iam::626963114819:role/rds-iceberg-dev-gha-tf-role

jobs:
  terraform-apply:
    name: Terraform Apply Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform fmt check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      - name: Terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve
